### PR TITLE
Gi 48 post new user volunteer role

### PR DESCRIPTION
**Pull request by ItsEricSun**
### ℹ️ Issue

Closes https://www.notion.so/mahekagg/GI-48-POST-new-user-Volunteer-role-1268b3e6836e800f8ce8c5c7647cae3d?pvs=4

### 📝 Description

Created a post endpoint for adding a new user as a volunteer.

Briefly list the changes made to the code:
1. Merged get user by ID into this branch
2. Changed the users endpoint to be "users" instead of "user"
3. Create post endpoint at /users/addVolunteer

### ✔️ Verification

Test JSON body:
```
{
    "firstName": "Eric",
    "lastName": "Sun",
    "phoneNumber": "1234567890",
    "email": "test@gmail.com",
    "zipCode": "02393",
    "birthDate": "January 1, 2001"
}
```

Before:
image
Postman:
image
After:
image
Getting with get user by ID endpoint:
image

### CODE REVIEW

**Comment by hams7504** [comment]
Could you merge 'main' into your branch? Looks like there are some merge conflicts

**Comment by ItsEricSun** [comment]
@hams7504 main is merged in now

**Review by hams7504 — APPROVED** [review]
Looks good!

**Review by SushiS1ay3r — APPROVED** [review]
LGTM!

**Pull request merged**
